=== themost-framework/themost/test/app/server/config/schemas/model-schema.json
{
  "id": "https://themost.io/schemas/2015/1/model-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "@id": {
      "type": "string",
      "description":"A string which represents a literal unique identifier for this model e.g. https://example.com/models/User"
    },
    "name": {
      "type": "string",
      "description":"A string which represents the name of this model e.g. Order, Customer, Person etc"
    },
    "id": {
      "type": "number",
      "description":"An optional numeric identifier for this model e.g. 9587891"
    },
    "title": {
      "type": "string",
      "description":"A string which represents the title of this e.g. Supplier Orders, Person Followers etc"
    },
    "inherits": {
      "type": "string",
      "description":"A string which represents the model which is inherited by this model e.g. User inherits Account, Person inherits Party etc"
    },
    "implements": {
      "type": "string",
      "description":"A string which represents the model which is implemented by this model e.g. ActionStatusType model implements Enumeration model etc"
    },
    "sealed": {
      "default": false,
      "type": "boolean",
      "description": "A boolean which indicates whether this model is being upgraded automatically or not. The default value is false."
    },
    "abstract": {
      "default": false,
      "type": "boolean",
      "description": "A boolean which indicates whether this model is an abstract model or not. The default value is false."
    },
    "source": {
      "type": "string",
      "description": "A string which holds the database object of this model. If this property is missing the database object's name is the concatenation of the model's name and the keyword 'Base' e.g. UserBase, PersonBase etc"
    },
    "view": {
      "type": "string",
      "description": "A string which holds the database object that is going to be used for fetching data. If this property is missing this database object's name is the concatenation of the model's name and the keyword 'Data' e.g. UserData, PersonData etc"
    },
    "version": {
      "default":"1.0",
      "type": "string",
      "pattern":"^[0-9]+\\.[0-9]+(\\.[0-9]+)?$",
      "description": "A string which represents the version of the model's schema. This version is going to be used in model upgrade operations e.g. 1.0, 0.1.2 etc"
    },
    "caching":{
      "default": "none",
      "type":"string",
      "enum": ["none", "always", "conditional"],
      "description":"A boolean which indicates whether model data will be cached or not. The default value is none -no caching-. A conditional caching allows developers to control caching mechanism while fetching data."
    },
    "fields": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@id": {
            "type": "string",
            "description":"A string which represents a literal unique identifier for this attribute e.g. https://example.com/models/attributes/name"
          },
          "description": {
            "type": "string",
            "description":"A string which represents a short description of this attribute"
          },
          "name": {
            "type": "string",
            "description":"A string which represents the name of this attribute e.g. title, description, dateCreated etc"
          },
          "title": {
            "type": "string",
            "description":"A string which represents a title for this attribute e.g. Date Created etc"
          },
          "type": {
            "type": "string",
            "description":"A string which represents the type of this attribute e.g. Counter, Integer, Number, Text etc"
          },
          "size": {
            "type": "number",
            "description":"A number which represents the maximum size for this attribute e.g. the size of a text field etc"
          },
          "nullable": {
            "default":true,
            "type": "boolean",
            "description": "A boolean which indicates whether this attribute is nullable or not."
          },
          "primary": {
            "type": "boolean",
            "description": "A boolean which indicates whether this attribute is a key column or not."
          },
          "indexed": {
            "default":false,
            "type": "boolean",
            "description": "A boolean which indicates whether this attribute is an indexed column or not."
          },
          "property": {
            "type": "string",
            "description":"A string which optionally represents the name of this attribute in object mapping. This name may defer from the name of the database field."
          },
          "many": {
            "type": "boolean",
            "description": "A boolean value which indicates whether this attribute represents an one-to-many or many-to-many association between two models."
          },
          "expandable": {
            "default":false,
            "type": "boolean",
            "description": "A boolean value which indicates whether the associated object(s) will be automatically expanded or not."
          },
          "mapping": {
            "type": "object",
            "properties": {
              "associationType": {
                "type": "string",
                "enum": ["association", "junction" ]
              },
              "associationAdapter": {
                "type": "string"
              },
              "parentModel": {
                "type": "string"
              },
              "parentField": {
                "type": "string"
              },
              "childModel": {
                "type": "string"
              },
              "childField": {
                "type": "string"
              },
              "cascade": {
                "type": "string",
                "enum": ["delete", "none"]
              }
            }
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "constraints": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description":"A string which represents the type of this constraint e.g. unique",
            "enum": ["unique"]
          },
          "description": {
            "type": "string",
            "description": "A short description for this constraint e.g. Unique identifier field must be unique across different records."
          },
          "fields": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "type"
        ]
      }
    },
    "eventListeners": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description":"A string which the name of this event listener e.g. update person user listener"
          },
          "type": {
            "type": "string",
            "description": "A string which represents the path of the module that exports this listener. This path may be a relative to execution folder path of a module exists in package modules e.g. ./listeners/add-user-listener or my-module/send-mail-listener"
          }
        },
        "required": [
          "type"
        ]
      }
    },
    "privileges": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "mask": {
            "default":15,
            "type": "number",
            "description":"A number which represents permission mask (1=Read,2=Create,4=Update,8=Delete,16=Execute)",
            "enum":[1,2,4,8,15,16]
          },
          "type": {
            "type": "string",
            "enum":["self","global","parent","item"],
            "description": "A string which represents the permission scope."
          },
          "account": {
            "type": "string",
            "description": "A string which represents the name of the security group where this privilege will be applied e.g. Administrators, Sales etc."
          },
          "filter": {
            "type": "string",
            "description": "A string which represents a filter expression for this privilege. This attribute is used for self privileges which are commonly derived from user's attributes e.g. 'owner eq me()' or 'orderStatus eq 1 and customer eq me()' etc."
          }
        },
        "required": [
          "mask",
          "type"
        ]
      }
    }
  },
  "required": [
    "name", "title", "version"
  ]
}

=== themost-framework/themost/test/event/server/config/models/PersonAvailability.json
{
    "@id": "http://schema.org/PersonAvailability",
    "name": "PersonAvailability",
    "title": "PersonAvailability",
    "abstract": false,
    "sealed": false,
    "version": "1.0",
    "fields": [
        {
            "@id": "https://themost.io/schemas/id",
            "name": "id",
            "title": "id",
            "description": "The identifier of the item.",
            "type": "Counter",
            "primary": true
        },
        {
            "@id": "http://schema.org/contributor",
            "name": "person",
            "title": "person",
            "type": "Person"
        },
        {
            "@id": "http://schema.org/eventHoursSpecification",
            "name": "eventHoursSpecification",
            "title": "eventHoursSpecification",
            "description": "Event Hours Specification.",
            "type": "EventHoursSpecification"
        },
        {
            "@id": "https://themost.io/schemas/conditional",
            "name": "conditional",
            "title": "Conditional",
            "type": "Boolean",
            "nullable": false,
            "value": "javascript:return false;"
        }
    ],
    "privileges": [
        {
            "mask": 1,
            "type": "global",
            "account": "*"
        },
        {
            "mask": 15,
            "type": "global"
        },
        {
            "mask": 15,
            "type": "global",
            "account": "Administrators"
        }
    ]
}
